language: node_js
node_js:
- '8'
addons:
  ssh_known_hosts: 104.211.299.97
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
# install:
#   - sudo apt-get install -y sshpass
deploy:
  provider: script
  skip_cleanup: true
  script: bash deploy.sh
  on:
    branch: master

