sudo: required
dist: xenial
language: node_js
node_js:
- '8'
addons:
  ssh_known_hosts: 104.211.299.97
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_e6d17770d077_key -iv $encrypted_e6d17770d077_iv
  -in deploy_key.enc -out deploy_key -d
- sudo apt-get install -y sshpass
- npm install -g create-react-app
before_script:
- npm test
- npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: bash deployment/deploy.sh
  on:
    branch: master
