language: node_js
node_js:
- '8'
addons:
  ssh_known_hosts: 104.211.299.97
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
# before_install:
# - openssl aes-256-cbc -K $encrypted_5688ddba367c_key -iv $encrypted_5688ddba367c_iv
#   -in deploy_rsa.enc -out /tmp/deploy_rsa -d
# - eval "$(ssh-agent -s)"
# - chmod 600 /tmp/deploy_rsa
# - ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: bash deploy.sh
  on:
    branch: master

