sudo: required
dist: xenial
language: node_js
node_js:
- '8'
addons:
  ssh_known_hosts: 104.211.299.97
cache:
  directories:
  - node_modules
before_install:
  - sudo apt-get install -y sshpass
  - npm install -g create-react-app
before_script:
- npm test
- npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: deployment/bash deploy.sh
  on:
    branch: master

